### PR TITLE
Make Dask progress bars optional

### LINKED ISSUE #95: Disable progress bars
Would be nice to provide an option to disable Dask progress bars (they make log files from a non-interactive run hard to read). [Seems like](https://stackoverflow.com/a/43121416) it is possible to unregister all that may have been registered (e.g. in monetio). Just need to implement a MM config option.

### PR DESCRIPTION
**Pull request by zmoon**
Resolves #95 

References:
* [Dask Diagnostics (local)](https://docs.dask.org/en/latest/diagnostics-local.html)
* [outdated SO answer about removing](https://stackoverflow.com/questions/43119440/how-to-unregister-all-progressbars/43121416#43121416)
* [PR describing new config methods](https://github.com/dask/dask/pull/3502)

### CODE REVIEW

**Comment by zmoon** [comment]
@rschwant I put this in `analysis.read_control()` method. Does that seem like a good place? Also are you ok with defaulting to false? Or do you want default true?

**Comment by zmoon** [comment]
Don't understand the docs build failure. Same Sphinx version as when it was passing recently (4.5.0).

**Comment by rschwant** [comment]
@zmoon Adding this to the analysis section seems like a good place to me. I also agree let's default to false and if people need to output these diagnostics they can set the value to true. I tested the commands in another jupyter notebook and they worked for me, so I can review this if needed too. Not sure either why the docs are failing now?

**Comment by zmoon** [comment]
@rschwant thanks for testing the commands!

**Review by rschwant — APPROVED** [review]
Looks good!

**Comment by zmoon** [comment]
Thanks @rschwant

**Pull request merged**
