### PR TITLE
Merge Develop to Main

### PR DESCRIPTION
**Pull request by rschwant**
Merge develop to main to create version 0.1 of MELODIES MONET to create first conda environment and a working version of all new applications for the Oct 2024 tutorial. 

This incorporates for the first time aircraft and satellite capabilities into the main branch.

### CODE REVIEW

**Comment by rschwant** [comment]
I checked all my scripts and they run well. I also skimmed through the code. I think this is ready to be our main branch. Can everyone else also double check and note if you see any problems? Let's try to get this done tomorrow morning so Zach can get started on the conda release. Thanks!

**Comment by blychs** [comment]
My code is running fine, including surface and tempo

**Review by mbruckner-work — COMMENTED** [review]
My satellite analyses worked.

**Review by blychs — APPROVED** [review]
Becky's, Maggie's and my code are working.

**Comment by rschwant** [comment]
I tested all aircraft components, so this is working well.

**Comment by mlirenzhenmayi** [comment]
The tropomi components are tested and working well.

**Pull request merged**
