### PR TITLE
Update machine-specific-install.rst

### PR DESCRIPTION
**Pull request by lkemmons**
A few clarifications in the cheyenne section.

### CODE REVIEW

**Comment by lkemmons** [comment]
Sorry - I'm not sure how to do that.

**Comment by zmoon** [comment]
> Sorry - I'm not sure how to do that.

That's ok, I can do it. But you don't mind if I do?

**Comment by lkemmons** [comment]
That would be great, thanks.
Louisa

**Comment by zmoon** [comment]
Moved these changes to #70

**Pull request closed without merging**
