### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by lkemmons**
people get permission errors with the "git@github.com:" address.

### CODE REVIEW

**Comment by zmoon** [comment]
Could you say more about the errors? On Linux the SSH clone can be more convenient than the HTTPS clone.

**Comment by zmoon** [comment]
@dwfncar do you want to weigh in?

**Comment by lkemmons** [comment]
I had permission errors installing melodies-monet on cheyenne with the git@github.com command.
Another user, using MacOS Catalina got these errors:
(melodies-monet) [Xeon:~/melodies] cbardeen% git clone [git@github.com](mailto:git@github.com):noaa-oar-arl/monetio.git
Cloning into 'monetio'...
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(melodies-monet) [Xeon:~/melodies] cbardeen% git clone [git@github.com](mailto:git@github.com):noaa-oar-arl/monet.git
Cloning into 'monet'...
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zmoon** [comment]
If you create a public/private RSA key pair on Cheyenne/Casper and then add the public one to your https://github.com/settings/keys it should work.

**Comment by lkemmons** [comment]
We could include both - say use what works - and maybe you could add an explanation of what the ssh clone is more convenient.

**Comment by zmoon** [comment]
@rschwant anything to add about your experience?

**Comment by lkemmons** [comment]
I didn't have to enter a password using the weblink - maybe that changed
when melodies became public?

**Comment by zmoon** [comment]
> I didn't have to enter a password using the weblink

You don't need to enter the password/token to clone the repo with HTTPS. But in my experience on Linux you do need it if you want to push/pull/whatnot.

**Comment by rschwant** [comment]
Setting up an ssh account is needed to do the git@github.com: 

Before the repository was public you had to set up an ssh key in order to clone the repository because it was private.
Maybe we can just recommend people set up an ssh account. This is definitely the easiest way to use github and recommended by github to setup. Maybe we can add something like the following:

If you are new to GitHub, check out this [Github tutorial](http://jlord.us/git-it/index.html). We recommend adding an [ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account). If you do not add an ssh key, you will need to clone the repository with the following command instead of the one recommended below: git clone https://github.com/NOAA-CSL/MELODIES-MONET

What do you think about this @zmoon and @lkemmons

**Comment by zmoon** [comment]
Yeah I think that sounds good. I can add that info as a footnote on this this docs page and reference it in the relevant section(s)?

**Comment by rschwant** [comment]
Yes thanks Zach that would be great.

**Comment by zmoon** [comment]
I added some notes about this to both install docs pages as part of #70. Thanks @lkemmons and @rschwant for the discussion.

**Pull request closed without merging**
