### PR TITLE
CLI: get data from ISH and ISH-Lite

### LINKED ISSUE #232: Add ISH and ISH-lite readers to MELODIES MONET
Add a reader for MONETIO / MELODIES MONET for synoptic surface meteorological data. There is an ISH-lite and ISH reader in MONETIO and WIP command-line download tools for MELODIES MONET from Zach and Jordan, but ISH has some issues still, so we just need to get this fixed, finalized, and into the develop branch.

### PR DESCRIPTION
**Pull request by zmoon**
`melodies-monet get-ish` and `get-ish-lite`

cc: @jordanschnell 

xref: noaa-oar-arl/monetio#157

Closes #232

### CODE REVIEW

**Comment by zmoon** [comment]
@jordanschnell I compared the file you gave me to this branch and the only differences were related to being able to specify the bounding box. I was able to get a working implementation of the box argument and I added it to `get-ish` as well. Here's an example with a small box (which I also use in the test I added):

```sh
melodies-monet get-ish-lite -s 2023-01-01 -e '2023-01-01 23:00' --box 39.5 -105.75 40.5 -104.75 --debug --verbose
```

**Comment by zmoon** [comment]
Note: In the merge (aa33d33), undid the change in 9de4ea4

**Review by jordanschnell — APPROVED** [review]
Works as expected, approved.

**Review by rschwant — APPROVED** [review]
Thanks Zach, this looks great. Thanks for adding this in!

**Comment by zmoon** [comment]
Thanks @jordanschnell and @rschwant

**Pull request merged**
