### PR TITLE
Add ability to pair model with mobile drive data and single ground site data

### PR DESCRIPTION
**Pull request by colin-harkins**
This is a draft PR for modifications to the develop_aircraft branch to add the ability to pair with mobile drive data and data from stationary ground sites. 

Currently the functionality for pairing with mobile drive data is implemented and I will add the ability to pair with data from a single ground site, and clean up the code tomorrow.

### CODE REVIEW

**Comment by quaz115** [comment]
@zmoon Wanted to get your suggestion on this error related to plotting I am getting with this PR:
Looks like the issue is potentially with pydecorate. @colin-harkins mentioned you actually fixed this in the github latest version of pydecorate (https://github.com/pytroll/pydecorate/issues/47) but a new version hasn't been put on conda?
Anyway we can limit version of pillow to a more depracated version (currently this PR uses 10.0) to avoid this error 

                                      ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[47], line 2
      1 #And this generates all the plots.
----> 2 an.plotting()

File ~/MM_developaircraft_ground_mobileadded_ColinPR185Test/MELODIES-MONET/melodies_monet/driver.py:1257, in analysis.plotting(self)
   1255     # At the end save the plot.
   1256     if p_index == len(pair_labels) - 1:
-> 1257         savefig(outname + '.png', logo_height=150)
   1258         del (ax, fig_dict, plot_dict, text_dict, obs_dict, obs_plot_dict) #Clear axis for next plot.
   1259 if plot_type.lower() == 'boxplot':

File ~/MM_developaircraft_ground_mobileadded_ColinPR185Test/monet/monet/plots/__init__.py:141, in savefig(fname, loc, decorate, logo, logo_height, **kwargs)
    139 else:
    140     raise ValueError(f"invalid `loc` {loc!r}")
--> 141 dc.add_logo(logo, **add_logo_kwargs)
    143 # PIL.Image will determine format from the filename extension
    144 img.save(fname)

File ~/anaconda3/envs/mm_colin_developaircraftPR185Test/lib/python3.9/site-packages/pydecorate/decorator_agg.py:48, in DecoratorAGG.add_logo(self, logo_path, **kwargs)
     47 def add_logo(self, logo_path, **kwargs):
---> 48     self._add_logo(logo_path, **kwargs)

File ~/anaconda3/envs/mm_colin_developaircraftPR185Test/lib/python3.9/site-packages/pydecorate/decorator_base.py:357, in DecoratorBase._add_logo(self, logo_path, **kwargs)
    354     nyi = int(round(nxi * aspect))
    355     ny = nyi + 2 * my
--> 357 logo = logo.resize((nxi, nyi), resample=Image.ANTIALIAS)
    359 # draw base
    360 px = self.style["propagation"][0] + self.style["newline_propagation"][0]

AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by zmoon** [comment]
Yeah, current workaround is to install `pydecorate<10` in your env.

**Comment by quaz115** [comment]
> Yeah, current workaround is to install `pydecorate<10` in your env.
> 
> Currently I have the env for the docs and CI setup this way. But yeah once pydecorate does a release that shouldn't be needed.

Yes works now, once i switch to pillows 9.5 in my conda env

**Review by quaz115 — COMMENTED** [review]
Currently works with the workaround of installing 'pillows'< 10:

pip install --force-reinstall -v "Pillow==9.5.0"

Note: New example yaml files (examples/yaml/control_hrrr-smoke_mobile.yaml and examples/yaml/control_wrfchem_ground.yaml) are good templates to compare model and obs, would need preprocessing of standard output files (say wrfout) if OBS variable is a combination of certain model variables (say no3ai+no3aj ~ PM1 NO3 observation)---> Future capability to be added ?

**Comment by quaz115** [comment]
@colin-harkins is this ready for merge now, we can also work to merge #181 with this? @zmoon any further reviews for these two PRs ?

**Pull request merged**
