### PR TITLE
add real-scorecard to MONET

### PR DESCRIPTION
**Pull request by btang1**
add real-score card to MONET

note #219 should be merged before this

### CODE REVIEW

**Review by rschwant — COMMENTED** [review]
The real-scorecard updates and description look good here. My concern is it looks like the multi-boxplot stuff is also in this pull request. But this already got merged to develop and I think is what is causing the merge conflicts in this pull request. @zmoon do you have suggestions to Beiming on how to fix this within GitHub, so this pull request only updates the scorecard components?

**Comment by zmoon** [comment]
@rschwant this has to be fixed locally on the command line (by merging the upstream develop branch into @btang1 's branch), @btang1 has some experience resolving merge conflicts this way already.

**Comment by rschwant** [comment]
@btang1 you mentioned last week that this was ready, but it looks like there are still merge conflicts? I can review this Thurs/Fri next week. Just let me know when it is ready.

**Comment by btang1** [comment]
> @btang1 you mentioned last week that this was ready, but it looks like there are still merge conflicts? I can review this Thurs/Fri next week. Just let me know when it is ready.

Thanks will address the merge problem!

**Comment by btang1** [comment]
@rschwant Hi Becky, @zmoon Helped me fix the merge bug. now we are good to merge. could you please take a look?

**Review by rschwant — APPROVED** [review]
Looks good!

**Comment by rschwant** [comment]
@btang1, this looks good. Although GitHub still says there are some merge conflicts that need to be resolved before merging. Can you update these and then I can merge this in? I don't see any more problems with the multi-boxplot, so maybe these are other problems?

**Comment by rschwant** [comment]
Maybe this is because I merged in your other pull request. And this caused some conflicts with this code now?

**Comment by btang1** [comment]
@rschwant Hi Becky, I have merged changes from CSI to scorecard. and test it example output in: https://github.com/btang1/MELODIES-MONET/blob/real-scorecard/docs/examples/airnow_wrfchem.ipynb.
now it should be ready to merge. could you please let me know if it works?

**Comment by rschwant** [comment]
@btang1 Just to add this here too. Can you fix the error in this file? https://github.com/btang1/MELODIES-MONET/blob/real-scorecard/docs/examples/airnow_wrfchem.ipynb. It looks like for the csi plot, you do not define a region_bx, so it shouldn't be listed on line 1989 to delete? Probably when you did the merge fix this did not merge perfectly. So I think you need to delete "region_bx" from this line and re-run.

**Comment by rschwant** [comment]
This works now thanks @zmoon and @btang1! I'm merging this in now, so that NCAR's examples work properly.

**Comment by btang1** [comment]
@rschwant @zmoon thank you so much!!!!

**Pull request merged**
