### PR TITLE
Implementation and testing of util.grid_util.update_sparse_data_grid

### PR DESCRIPTION
**Pull request by davidfillmore**
util.grid_util.update_sparse_data_grid will be used in the processing of satellite swath data,
but may be eventually useful for other datasets.
Perhaps will evolve into a full SparseDataGrid class?
Note unix timestamps (seconds since 1970 Jan 01) are assumed to be available in the obs datasets.
These need to be added to any readers that may send data arrays to this method.

To test:
cd tests
python setup_obs.py test_grid.yaml --nfile 3
python test_grid.py

### CODE REVIEW

**Comment by davidfillmore** [comment]
Working to fix test and docs checks

**Comment by zmoon** [comment]
Just noting expandvars (https://github.com/NOAA-CSL/MELODIES-MONET/pull/91) should be merged before this.

**Comment by zmoon** [comment]
@dwfncar I will work on getting the new test picked up in the CI

**Review by rschwant — APPROVED** [review]
Looks good! You can merge this this to develop when you are ready. This will not impact the rest of the code, so I'm fine with these new utilities being added in for now and you can document them later once they are used in the main code.

**Pull request merged**
